# Generated by Django 5.0.4 on 2024-05-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovieLIst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Year_release", models.DateField(auto_created=True)),
                ("Title", models.CharField(max_length=200)),
                (
                    "Poster",
                    models.FileField(default="avatar.png", upload_to="users/avatars"),
                ),
                ("Genre", models.CharField(max_length=200)),
                ("Rating", models.FloatField(max_length=3)),
                ("Metacritic_rating", models.FloatField(max_length=3)),
                ("Runtime", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "movie_listing",
            },
        ),
    ]
