# Generated by Django 5.0.4 on 2024-05-06 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Genre_name",
                    models.CharField(
                        choices=[
                            ("action", "Action"),
                            ("romanic", "Romantic"),
                            ("comedy", "Comedy"),
                            ("thriller", "Thriller"),
                        ],
                        default="action",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "genre",
            },
        ),
        migrations.AlterField(
            model_name="movielist",
            name="Genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movie_app.genre"
            ),
        ),
    ]
