# Generated by Django 5.0.4 on 2024-05-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0002_genre_alter_movielist_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="Genre_name",
            field=models.CharField(default="action", max_length=100),
        ),
    ]
